// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!! THIS FILE IS GENERATED AUTOMATICALLY, DO NOT CHANGE IT !!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/*
 *  ARDroneGeneratedTypes.h
 *  ARDroneEngine
 *
 *  Automatically generated.
 *  Copyright 2010 Parrot SA. All rights reserved.
 *
 */
#ifndef _ARDRONE_GENERATED_TYPES_H_
#define _ARDRONE_GENERATED_TYPES_H_

#define ARDRONE_MAX_ENEMIES 4

typedef enum {
ARDRONE_LED_ANIMATION_BLINK_GREEN_RED,
ARDRONE_LED_ANIMATION_BLINK_GREEN,
ARDRONE_LED_ANIMATION_BLINK_RED,
ARDRONE_LED_ANIMATION_BLINK_ORANGE,
ARDRONE_LED_ANIMATION_SNAKE_GREEN_RED,
ARDRONE_LED_ANIMATION_FIRE,
ARDRONE_LED_ANIMATION_STANDARD,
ARDRONE_LED_ANIMATION_RED,
ARDRONE_LED_ANIMATION_GREEN,
ARDRONE_LED_ANIMATION_RED_SNAKE,
ARDRONE_LED_ANIMATION_BLANK,
ARDRONE_LED_ANIMATION_RIGHT_MISSILE,
ARDRONE_LED_ANIMATION_LEFT_MISSILE,
ARDRONE_LED_ANIMATION_DOUBLE_MISSILE,
ARDRONE_LED_ANIMATION_FRONT_LEFT_GREEN_OTHERS_RED,
ARDRONE_LED_ANIMATION_FRONT_RIGHT_GREEN_OTHERS_RED,
ARDRONE_LED_ANIMATION_REAR_RIGHT_GREEN_OTHERS_RED,
ARDRONE_LED_ANIMATION_REAR_LEFT_GREEN_OTHERS_RED,
ARDRONE_LED_ANIMATION_LEFT_GREEN_RIGHT_RED,
ARDRONE_LED_ANIMATION_LEFT_RED_RIGHT_GREEN,
ARDRONE_LED_ANIMATION_BLINK_STANDARD,
} ARDRONE_LED_ANIMATION;

typedef enum {
ARDRONE_ANIMATION_PHI_M30_DEG=0,
ARDRONE_ANIMATION_PHI_30_DEG,
ARDRONE_ANIMATION_THETA_M30_DEG,
ARDRONE_ANIMATION_THETA_30_DEG,
ARDRONE_ANIMATION_THETA_20DEG_YAW_200DEG,
ARDRONE_ANIMATION_THETA_20DEG_YAW_M200DEG,
ARDRONE_ANIMATION_TURNAROUND,
ARDRONE_ANIMATION_TURNAROUND_GODOWN,
ARDRONE_ANIMATION_YAW_SHAKE,
ARDRONE_ANIMATION_YAW_DANCE,
ARDRONE_ANIMATION_PHI_DANCE,
ARDRONE_ANIMATION_THETA_DANCE,
ARDRONE_ANIMATION_VZ_DANCE,
ARDRONE_ANIMATION_WAVE,
ARDRONE_ANIMATION_PHI_THETA_MIXED,
ARDRONE_ANIMATION_DOUBLE_PHI_THETA_MIXED,
ARDRONE_ANIMATION_FLIP_AHEAD,
ARDRONE_ANIMATION_FLIP_BEHIND,
ARDRONE_ANIMATION_FLIP_LEFT,
ARDRONE_ANIMATION_FLIP_RIGHT,
} ARDRONE_ANIMATION;

typedef enum {
ARDRONE_CAMERA_DETECTION_HORIZONTAL=0,
ARDRONE_CAMERA_DETECTION_VERTICAL,
ARDRONE_CAMERA_DETECTION_VISION,
ARDRONE_CAMERA_DETECTION_NONE,
ARDRONE_CAMERA_DETECTION_COCARDE,
ARDRONE_CAMERA_DETECTION_ORIENTED_COCARDE,
ARDRONE_CAMERA_DETECTION_STRIPE,
ARDRONE_CAMERA_DETECTION_H_COCARDE,
ARDRONE_CAMERA_DETECTION_H_ORIENTED_COCARDE,
ARDRONE_CAMERA_DETECTION_STRIPE_V,
ARDRONE_CAMERA_DETECTION_MULTIPLE_DETECTION_MODE,
ARDRONE_CAMERA_DETECTION_CAP,
ARDRONE_CAMERA_DETECTION_ORIENTED_COCARDE_BW,
ARDRONE_CAMERA_DETECTION_VISION_V2,
ARDRONE_CAMERA_DETECTION_TOWER_SIDE,
ARDRONE_CAMERA_DETECTION_NUM,
} ARDRONE_CAMERA_DETECTION_TYPE;

typedef enum {
ARDRONE_VIDEO_CHANNEL_FIRST=0,
ARDRONE_VIDEO_CHANNEL_HORI=ARDRONE_VIDEO_CHANNEL_FIRST,
ARDRONE_VIDEO_CHANNEL_VERT,
ARDRONE_VIDEO_CHANNEL_LARGE_HORI_SMALL_VERT,
ARDRONE_VIDEO_CHANNEL_LARGE_VERT_SMALL_HORI,
ARDRONE_VIDEO_CHANNEL_LAST=ARDRONE_VIDEO_CHANNEL_LARGE_VERT_SMALL_HORI,
ARDRONE_VIDEO_CHANNEL_NEXT,
} ARDRONE_VIDEO_CHANNEL;

typedef enum {
ARDRONE_VARIABLE_BITRATE_MODE_DISABLED=0,
ARDRONE_VARIABLE_BITRATE_MODE_DYNAMIC,
ARDRONE_VARIABLE_BITRATE_MANUAL
} ARDRONE_VARIABLE_BITRATE;

typedef enum {
ARDRONE_ENEMY_COLOR_ORANGE_GREEN=1,
ARDRONE_ENEMY_COLOR_ORANGE_YELLOW,
ARDRONE_ENEMY_COLOR_ORANGE_BLUE,
ARDRONE_ENEMY_COLOR_ARRACE_FINISH_LINE=0x10,
ARDRONE_ENEMY_COLOR_ARRACE_DONUT=0x11
} ARDRONE_ENEMY_COLOR;

typedef enum {
ARDRONE_CONFIG_KEY_VIDEO_ENABLE,//BOOLEAN
ARDRONE_CONFIG_KEY_CONTROL_LEVEL,//INT
ARDRONE_CONFIG_KEY_EULER_ANGLE_MAX,//FLOAT
ARDRONE_CONFIG_KEY_ALTITUDE_MAX,//INT
ARDRONE_CONFIG_KEY_ALTITUDE_MIN,//INT
ARDRONE_CONFIG_KEY_CONTROL_IPHONE_TILT,//FLOAT
ARDRONE_CONFIG_KEY_CONTROL_VZ_MAX,//FLOAT
ARDRONE_CONFIG_KEY_CONTROL_YAW,//FLOAT
ARDRONE_CONFIG_KEY_OUTDOOR,//BOOLEAN
ARDRONE_CONFIG_KEY_FLIGHT_WITHOUT_SHELL,//BOOLEAN
ARDRONE_CONFIG_KEY_AUTONOMOUS_FLIGHT,//BOOLEAN
ARDRONE_CONFIG_KEY_MANUAL_TRIM,//BOOLEAN
ARDRONE_CONFIG_KEY_INDOOR_EULER_ANGLE_MAX,//FLOAT
ARDRONE_CONFIG_KEY_INDOOR_CONTROL_VZ_MAX,//FLOAT
ARDRONE_CONFIG_KEY_INDOOR_CONTROL_YAW,//FLOAT
ARDRONE_CONFIG_KEY_OUTDOOR_EULER_ANGLE_MAX,//FLOAT
ARDRONE_CONFIG_KEY_OUTDOOR_CONTROL_VZ_MAX,//FLOAT
ARDRONE_CONFIG_KEY_OUTDOOR_CONTROL_YAW,//FLOAT
ARDRONE_CONFIG_KEY_FLYING_MODE,//INT
ARDRONE_CONFIG_KEY_HOVERING_RANGE,//INT
ARDRONE_CONFIG_KEY_FLIGHT_ANIM,//STRING
ARDRONE_CONFIG_KEY_TRAVELLING_MODE,//STRING
ARDRONE_CONFIG_KEY_TRAVELLING_ENABLE,//BOOLEAN
ARDRONE_CONFIG_KEY_SSID_SINGLE_PLAYER,//STRING
ARDRONE_CONFIG_KEY_SSID_MULTI_PLAYER,//STRING
ARDRONE_CONFIG_KEY_WIFI_MODE,//INT
ARDRONE_CONFIG_KEY_WIFI_RATE,//INT
ARDRONE_CONFIG_KEY_OWNER_MAC,//STRING
ARDRONE_CONFIG_KEY_CODEC_FPS,//INT
ARDRONE_CONFIG_KEY_VIDEO_CODEC,//INT
ARDRONE_CONFIG_KEY_VIDEO_SLICES,//INT
ARDRONE_CONFIG_KEY_VIDEO_LIVE_SOCKET,//INT
ARDRONE_CONFIG_KEY_BITRATE,//INT
ARDRONE_CONFIG_KEY_MAX_BITRATE,//INT
ARDRONE_CONFIG_KEY_BITRATE_CTRL_MODE,//INT
ARDRONE_CONFIG_KEY_BITRATE_STORAGE,//INT
ARDRONE_CONFIG_KEY_VIDEO_CHANNEL,//INT
ARDRONE_CONFIG_KEY_VIDEO_ON_USB,//BOOLEAN
ARDRONE_CONFIG_KEY_VIDEO_FILE_INDEX,//INT
ARDRONE_CONFIG_KEY_LEDS_ANIM,//STRING
ARDRONE_CONFIG_KEY_ENEMY_COLORS,//INT
ARDRONE_CONFIG_KEY_GROUNDSTRIPE_COLORS,//INT
ARDRONE_CONFIG_KEY_ENEMY_WITHOUT_SHELL,//INT
ARDRONE_CONFIG_KEY_DETECT_TYPE,//INT
ARDRONE_CONFIG_KEY_DETECTIONS_SELECT_H,//INT
ARDRONE_CONFIG_KEY_DETECTIONS_SELECT_V_HSYNC,//INT
ARDRONE_CONFIG_KEY_DETECTIONS_SELECT_V,//INT
ARDRONE_CONFIG_KEY_USERBOX_CMD,//STRING
ARDRONE_CONFIG_KEY_LATITUDE,//DOUBLE
ARDRONE_CONFIG_KEY_LONGITUDE,//DOUBLE
ARDRONE_CONFIG_KEY_ALTITUDE,//DOUBLE
} ARDRONE_CONFIG_KEYS;

typedef enum {
ARDRONE_VIDEO_CODEC_UVLC = 0x20,
ARDRONE_VIDEO_CODEC_P264 = 0x40,
MP4_ARDRONE_VIDEO_CODEC_360P = 0x80,
H264_ARDRONE_VIDEO_CODEC_360P = 0x81,
MP4_360P_H264_ARDRONE_VIDEO_CODEC_720P = 0x82,
H264_ARDRONE_VIDEO_CODEC_720P = 0x83,
MP4_360P_ARDRONE_VIDEO_CODEC_SLRS = 0x84,
H264_360P_ARDRONE_VIDEO_CODEC_SLRS = 0x85,
H264_720P_ARDRONE_VIDEO_CODEC_SLRS = 0x86,
H264_AUTO_ARDRONE_VIDEO_CODEC_RESIZE = 0x87,
} ARDRONE_VIDEO_CODEC;

typedef enum {
ARDRONE_FLYING_MODE_FREE_FLIGHT=0,
ARDRONE_FLYING_MODE_HOVER_ON_TOP_OF_ROUNDEL=1<<0,
ARDRONE_FLYING_MODE_HOVER_ON_TOP_OF_ORIENTED_ROUNDEL=1<<1,
} ARDRONE_FLYING_MODE;

typedef enum {
ARDRONE_ACADEMY_STATE_NONE,
ARDRONE_ACADEMY_STATE_CONNECTION,
ARDRONE_ACADEMY_STATE_PREPARE_PROCESS,
ARDRONE_ACADEMY_STATE_PROCESS,
ARDRONE_ACADEMY_STATE_FINISH_PROCESS,
ARDRONE_ACADEMY_STATE_DISCONNECTION,
ARDRONE_ACADEMY_STATE_MAX,
} ARDRONE_ACADEMY_STATE;

typedef enum {
ARDRONE_ACADEMY_RESULT_NONE,
ARDRONE_ACADEMY_RESULT_OK,
ARDRONE_ACADEMY_RESULT_FAILED,
} ARDRONE_ACADEMY_RESULT;

typedef enum {
ARDRONE_FLYING_STATE_LANDED=0,
ARDRONE_FLYING_STATE_FLYING,
ARDRONE_FLYING_STATE_TAKING_OFF,
ARDRONE_FLYING_STATE_LANDING,
} ARDRONE_FLYING_STATE;

#endif // _ARDRONE_GENERATED_TYPES_H_
